"""Pydantic models for InventoryManager (SCM-01).

All models are frozen (immutable) with extra="forbid" to enforce correctness
at construction boundaries (Phase 8 CR-05 discipline).

Models:
    ReorderRecommendation — represents a purchase recommendation draft pending HITL.
    InventoryAlert        — represents an emitted REORDER_ALERT for downstream routing.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ReorderRecommendation(BaseModel):
    """Purchase recommendation draft produced by InventoryManager (SCM-01).

    Frozen + extra=forbid to prevent post-construction mutation (CR-05).
    recommendation_id is a stable str derived from thread_id by the agent (CR-04);
    it is set externally at construction time — never generated by this model.

    Fields:
        sku_id:              SKU identifier (matches scm.sku_master.sku_id).
        current_qty:         Latest inventory quantity in Decimal.
        reorder_point:       Configured reorder threshold in Decimal.
        reorder_qty:         Fixed order quantity from sku_master in Decimal.
        lead_time_days:      Supplier lead time in calendar days.
        estimated_cost_eur:  Expected procurement cost = reorder_qty * unit_cost_eur.
        recommendation_id:   Stable correlation id (sha256 of AGENT_ID + thread_id, :32).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    sku_id: Annotated[str, Field(min_length=1, description="SKU identifier")]
    current_qty: Annotated[Decimal, Field(description="Current inventory quantity")]
    reorder_point: Annotated[Decimal, Field(description="Reorder threshold")]
    reorder_qty: Annotated[Decimal, Field(description="Fixed order quantity from sku_master")]
    lead_time_days: Annotated[int, Field(ge=0, description="Supplier lead time in days")]
    estimated_cost_eur: Annotated[Decimal, Field(description="Estimated procurement cost in EUR")]
    recommendation_id: Annotated[
        str,
        Field(
            min_length=1,
            description=(
                "Stable correlation id — sha256(AGENT_ID.thread_id)[:32]. "
                "NEVER a random uuid4 (CR-04)."
            ),
        ),
    ]


class InventoryAlert(BaseModel):
    """REORDER_ALERT emitted by InventoryManager as state output (SCM-01).

    The alert signals to downstream agents and the gateway that a procurement
    approval flow is pending. It is the trigger row before HITL sign-off.

    Frozen + extra=forbid.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    alert_type: Annotated[
        str,
        Field(default="REORDER_ALERT", description="Always REORDER_ALERT for SCM-01"),
    ] = "REORDER_ALERT"
    sku_id: Annotated[str, Field(min_length=1, description="SKU that triggered the alert")]
    recommendation_id: Annotated[str, Field(min_length=1, description="Stable recommendation id")]
    message: Annotated[str, Field(min_length=1, description="Human-readable alert message")]


__all__ = ["InventoryAlert", "ReorderRecommendation"]
