"""Pydantic models for EnergyOptimizer (SCM-02, Plan 09-03).

All models are frozen (immutable) with extra="forbid" to enforce correctness
at construction boundaries (Phase 8 CR-05 discipline).

Models:
    EnergyReading     — single reading from scm.energy_readings (row DTO).
    OffPeakProposal   — off-peak scheduling proposal pending supervisor HITL.
    EnergyAlert       — ENERGY_ALERT state output for downstream routing.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class EnergyReading(BaseModel):
    """Single row from scm.energy_readings (asyncpg row DTO).

    Frozen + extra=forbid.
    datetime fields arrive from asyncpg as tz-aware Python datetime objects.
    NEVER call .isoformat() on datetime params passed to asyncpg (Pitfall 7).

    Fields:
        ts:           Timestamp of the reading (tz-aware).
        asset_id:     Factory asset identifier.
        kwh:          Electricity consumed in kWh for this slot.
        kg_processed: kg of material processed; None when not measurable.
        is_peak_hour: True when the reading was during peak tariff hours.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    ts: Annotated[datetime, Field(description="Timestamp of the reading (tz-aware)")]
    asset_id: Annotated[str, Field(min_length=1, description="Factory asset identifier")]
    kwh: Annotated[float, Field(ge=0.0, description="kWh consumed in this slot")]
    kg_processed: Annotated[
        float | None,
        Field(default=None, description="kg processed; None when not measurable"),
    ] = None
    is_peak_hour: Annotated[
        bool,
        Field(default=False, description="True when reading was during peak tariff hours"),
    ] = False


class OffPeakProposal(BaseModel):
    """Off-peak scheduling proposal produced by EnergyOptimizer (SCM-02).

    Frozen + extra=forbid to prevent post-construction mutation (CR-05).
    proposal_id is a stable str derived from thread_id by the agent (CR-04);
    it is set externally at construction time — never generated by this model.

    Fields:
        process:              Factory process (e.g. 'dyeing', 'finishing').
        proposal_id:          Stable correlation id sha256(AGENT_ID.thread_id)[:32].
        enpi_actual:          Measured kWh/kg for the reporting period.
        enpi_baseline:        ISO 50001 target kWh/kg from scm.enpi_baseline.
        deviation_pct:        (actual - baseline) / baseline * 100.
        is_above_baseline:    True when EnPI is worse than target.
        off_peak_kwh_pct:     Current off-peak consumption fraction (%).
        recommended_window:   Description of the suggested off-peak shift window.
        expected_savings_pct: Estimated % reduction in energy cost if proposal
                              is adopted. Clamped to [0.0, 100.0] by the agent (CR-05).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    process: Annotated[str, Field(min_length=1, description="Factory process name")]
    proposal_id: Annotated[
        str,
        Field(
            min_length=1,
            description=(
                "Stable correlation id — sha256(AGENT_ID.thread_id)[:32]. "
                "NEVER a random uuid4 (CR-04)."
            ),
        ),
    ]
    enpi_actual: Annotated[
        float,
        Field(ge=0.0, description="Measured kWh/kg for the reporting period"),
    ]
    enpi_baseline: Annotated[
        float,
        Field(ge=0.0, description="ISO 50001 target kWh/kg from scm.enpi_baseline"),
    ]
    deviation_pct: Annotated[
        float,
        Field(description="(actual - baseline) / baseline * 100"),
    ]
    is_above_baseline: Annotated[
        bool,
        Field(description="True when enpi_actual > enpi_baseline"),
    ]
    off_peak_kwh_pct: Annotated[
        float,
        Field(ge=0.0, le=100.0, description="Current off-peak consumption fraction (%)"),
    ]
    recommended_window: Annotated[
        str,
        Field(
            min_length=1,
            description="Human-readable off-peak shift window recommendation",
        ),
    ]
    expected_savings_pct: Annotated[
        float,
        Field(
            ge=0.0,
            le=100.0,
            description=(
                "Estimated % cost reduction if proposal adopted. "
                "Clamped to [0, 100] by the agent before construction (CR-05)."
            ),
        ),
    ]


class EnergyAlert(BaseModel):
    """ENERGY_ALERT emitted by EnergyOptimizer as state output (SCM-02).

    Signals that an off-peak scheduling proposal is pending HITL sign-off.

    Frozen + extra=forbid.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    alert_type: Annotated[
        str,
        Field(default="ENERGY_ALERT", description="Always ENERGY_ALERT for SCM-02"),
    ] = "ENERGY_ALERT"
    process: Annotated[str, Field(min_length=1, description="Process that triggered the alert")]
    proposal_id: Annotated[str, Field(min_length=1, description="Stable proposal id")]
    message: Annotated[str, Field(min_length=1, description="Human-readable alert message")]


__all__ = ["EnergyAlert", "EnergyReading", "OffPeakProposal"]
