apiVersion: v2
name: api-gateway
description: Smart Factory Transformation - api-gateway service chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - smart-factory
  - api-gateway
home: https://github.com/fedcal/smart-factory-transformation
sources:
  - https://github.com/fedcal/smart-factory-transformation
maintainers:
  - name: fedcal
    email: fedcal01@gmail.com
