"""Parametrized equality + edge-case tests for source_uri resolution (Plan 05-12).

Gap closure for VERIFICATION.md gap 2 (KNW-07 PARTIAL / CR-02):
  - derive_source_uri(p) must equal MarkdownParser().parse(p).source_uri for the same path.
  - derive_source_uri must handle workspace / tmp / symlink / Windows-separator edge cases.

All four tests fail with ImportError in RED (path_utils.py does not exist yet).
"""

from __future__ import annotations

import os
from pathlib import Path
from textwrap import dedent

import pytest

from sft_knowledge.path_utils import derive_source_uri  # RED: ImportError expected
from sft_knowledge.parsers.markdown import MarkdownParser

WORKSPACE_ROOT = Path(__file__).resolve().parents[3]
SYNTHETIC_CORPUS = WORKSPACE_ROOT / "simulators" / "synthetic-corpus"


# ---------------------------------------------------------------------------
# Helper to write a minimal reviewed SOP in tmp_path
# ---------------------------------------------------------------------------


def _write_reviewed_sop(tmp_path: Path, sop_id: str = "SOP-TEST-URI-001") -> Path:
    p = tmp_path / f"{sop_id}-en.md"
    p.write_text(
        dedent(
            f"""\
            ---
            id: {sop_id}
            title: URI resolution fixture
            version: "1.0"
            lang: en
            status: reviewed
            acl_level: public
            asset_family: weaving
            tags: []
            related_glossary: []
            ---

            ## Scope

            Fixture body for source_uri resolution tests.
            """
        ),
        encoding="utf-8",
    )
    return p


# ---------------------------------------------------------------------------
# Test 1 — workspace path produces forward-slash-only corpus:// URI
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not SYNTHETIC_CORPUS.exists(),
    reason="simulators/synthetic-corpus/ not present in this checkout",
)
def test_derive_source_uri_workspace_file() -> None:
    """derive_source_uri(p) for an in-workspace SOP starts with corpus://simulators/synthetic-corpus/
    and contains only forward slashes (no backslashes)."""
    paths = sorted(SYNTHETIC_CORPUS.rglob("SOP-*.md"))
    assert paths, "Expected at least one SOP in synthetic-corpus"
    p = paths[0]

    uri = derive_source_uri(p)

    assert uri.startswith("corpus://simulators/synthetic-corpus/"), (
        f"Expected corpus://simulators/synthetic-corpus/... but got: {uri!r}"
    )
    assert "\\" not in uri, f"URI must not contain backslashes: {uri!r}"


# ---------------------------------------------------------------------------
# Test 2 — equality with MarkdownParser output (the key invariant)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not SYNTHETIC_CORPUS.exists(),
    reason="simulators/synthetic-corpus/ not present in this checkout",
)
async def test_derive_source_uri_equals_markdown_parser_output() -> None:
    """derive_source_uri(p) == MarkdownParser().parse(p).source_uri for the first reviewed SOP.

    This is the primary invariant: orchestrator and parser must agree on the URI so that
    state_store.get(URI) finds the row that state_store.upsert(URI) created.
    """
    paths = sorted(SYNTHETIC_CORPUS.rglob("SOP-*.md"))
    # Filter for reviewed SOPs (all Phase 5 SOPs have status: reviewed).
    reviewed: list[Path] = []
    for p in paths:
        try:
            import frontmatter as fm_lib
            post = fm_lib.load(str(p))
            if post.metadata.get("status") == "reviewed":
                reviewed.append(p)
        except Exception:  # noqa: BLE001
            continue

    if not reviewed:
        pytest.xfail(
            "No reviewed SOP found under simulators/synthetic-corpus/ "
            "— synthetic corpus should be generated by Phase 2 before Phase 5 tests run."
        )

    p = reviewed[0]
    parser = MarkdownParser()
    parsed = await parser.parse(p)
    assert parsed is not None, f"Expected a ParsedDoc for reviewed SOP {p}"

    helper_uri = derive_source_uri(p)
    parser_uri = parsed.source_uri

    assert helper_uri == parser_uri, (
        f"source_uri mismatch for {p!r}:\n"
        f"  derive_source_uri → {helper_uri!r}\n"
        f"  MarkdownParser    → {parser_uri!r}"
    )


# ---------------------------------------------------------------------------
# Test 3 — out-of-workspace tmp_path: leading slash stripped, no double //
# ---------------------------------------------------------------------------


def test_derive_source_uri_tmp_path_outside_workspace(tmp_path: Path) -> None:
    """derive_source_uri for an absolute tmp_path (outside workspace) starts with corpus://
    and must NOT contain // after the scheme (leading / is stripped)."""
    p = tmp_path / "outside-workspace.md"
    p.write_text("# dummy\n", encoding="utf-8")

    uri = derive_source_uri(p)

    assert uri.startswith("corpus://"), f"Must start with corpus://: {uri!r}"
    # The part after the scheme must not start with /  (leading slash stripped)
    after_scheme = uri[len("corpus://"):]
    assert not after_scheme.startswith("/"), (
        f"Leading / not stripped — double slash after scheme: {uri!r}"
    )
    assert "\\" not in uri, f"URI must not contain backslashes: {uri!r}"


# ---------------------------------------------------------------------------
# Test 4 — symlink inside workspace resolves to same URI as realpath
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not SYNTHETIC_CORPUS.exists(),
    reason="simulators/synthetic-corpus/ not present in this checkout",
)
def test_derive_source_uri_symlink_inside_workspace(tmp_path: Path) -> None:
    """A symlink in tmp_path pointing to an in-workspace SOP yields the same URI as the realpath.

    Both resolve through Path.resolve() so symlinks are transparent.
    """
    paths = sorted(SYNTHETIC_CORPUS.rglob("SOP-*.md"))
    assert paths, "Expected at least one SOP in synthetic-corpus"
    target = paths[0]

    symlink = tmp_path / "symlinked-sop.md"
    os.symlink(target, symlink)

    uri_via_symlink = derive_source_uri(symlink)
    uri_via_realpath = derive_source_uri(target.resolve())

    assert uri_via_symlink == uri_via_realpath, (
        f"Symlink and realpath must produce the same URI:\n"
        f"  symlink  → {uri_via_symlink!r}\n"
        f"  realpath → {uri_via_realpath!r}"
    )
