apiVersion: v1
kind: Service
metadata:
  name: {{ include "ot-bridge.fullname" . }}
  labels:
    {{- include "ot-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: opcua
      protocol: TCP
      name: opcua
  selector:
    {{- include "ot-bridge.selectorLabels" . | nindent 4 }}
