#!/usr/bin/env python3
"""
scripts/generate-assumption-pages.py

Generates IT and EN MkDocs Markdown pages from docs/assumptions/register.yaml.

Output files:
  - docs/docs/assumptions/index.md        — IT index table (sortable, material-tags)
  - docs/docs/en/assumptions/index.md     — EN index table
  - docs/docs/assumptions/A-NNN.md        — IT detail page per assumption (hidden: true)
  - docs/docs/en/assumptions/A-NNN.md     — EN detail page per assumption (hidden: true)

Design decisions (D-33, Open Question #3):
  - Detail pages have `hidden: true` in frontmatter: they are reachable via deep link
    from the index table but do NOT appear in the MkDocs sidebar nav.
  - Only docs/docs/assumptions/index.md is linked in mkdocs.yml nav.
  - Both IT and EN are generated in a single run to keep them symmetric.
  - Idempotency: sort stable, no timestamps, deterministic frontmatter key order,
    line endings always LF. Double-run produces zero git diff.

Usage:
    python3 scripts/generate-assumption-pages.py [--dry-run] [--check]

Exit codes:
    0 - Pages written (or dry-run completed / no drift in --check mode)
    1 - I/O or YAML error
    2 - Drift detected in --check mode (at least one file differs from on-disk content)
"""
import argparse
import sys
from pathlib import Path

import yaml

WORKSPACE_ROOT = Path(__file__).parent.parent

REGISTER = Path("docs/assumptions/register.yaml")

OUTPUTS: dict[str, Path] = {
    "it": Path("docs/docs/assumptions"),
    "en": Path("docs/docs/en/assumptions"),
}

_AUTOGENERATED_HEADER = (
    "<!-- AUTOGENERATED from docs/assumptions/register.yaml — DO NOT EDIT -->\n"
    "<!-- Rigenera con: python3 scripts/generate-assumption-pages.py -->\n"
)

# Localised string tables (IT / EN)
_STRINGS: dict[str, dict[str, str]] = {
    "it": {
        "index_h1": "Registro delle Assunzioni",
        "index_intro": (
            "Questo registro traccia le assunzioni esplicite del progetto Smart Factory Transformation "
            "su qualità dei dati, simulazione, limiti di scope, dipendenze esterne, "
            "requisiti normativi, sicurezza, performance e costo. "
            "Ogni assunzione è identificata da un id univoco (A-NNN), "
            "categorizzata e associata ai componenti impattati. "
            "La colonna **Affermazione** è troncata; fare clic sull'id per i dettagli completi."
        ),
        "col_id": "Id",
        "col_category": "Categoria",
        "col_statement": "Affermazione",
        "col_components": "Componenti",
        "col_status": "Stato",
        "field_id": "Identificativo",
        "field_statement": "Affermazione",
        "field_category": "Categoria",
        "field_components": "Componenti Impattati",
        "field_rationale": "Razionale",
        "field_validation": "Metodo di Validazione",
        "field_risk": "Rischio se Errata",
        "field_status": "Stato",
        "field_created": "Creata nella Fase",
        "field_reviewed": "Ultima Revisione nella Fase",
        "field_superseded": "Sostituita da",
        "null_label": "—",
        "page_title_prefix": "Assunzione",
    },
    "en": {
        "index_h1": "Assumption Register",
        "index_intro": (
            "This register tracks explicit project assumptions of the Smart Factory Transformation "
            "platform regarding data quality, simulation fidelity, scope limits, external dependencies, "
            "regulatory requirements, security, performance, and cost. "
            "Each assumption is identified by a unique id (A-NNN), categorised, and associated "
            "with the impacted components. "
            "The **Statement** column is truncated; click the id for full details."
        ),
        "col_id": "ID",
        "col_category": "Category",
        "col_statement": "Statement",
        "col_components": "Components",
        "col_status": "Status",
        "field_id": "ID",
        "field_statement": "Statement",
        "field_category": "Category",
        "field_components": "Affected Components",
        "field_rationale": "Rationale",
        "field_validation": "Validation Method",
        "field_risk": "Risk if Wrong",
        "field_status": "Status",
        "field_created": "Created in Phase",
        "field_reviewed": "Last Reviewed in Phase",
        "field_superseded": "Superseded By",
        "null_label": "—",
        "page_title_prefix": "Assumption",
    },
}

_STATEMENT_TRUNCATE = 80


def _truncate(text: str, max_len: int = _STATEMENT_TRUNCATE) -> str:
    """Truncate text to max_len characters, appending '...' if truncated."""
    text = text.replace("\n", " ").strip()
    if len(text) <= max_len:
        return text
    return text[:max_len].rstrip() + "..."


def render_index(entries: list[dict], lang: str) -> str:
    """
    Render the assumption index table for the given language.

    Returns a Markdown string. No timestamps (idempotency guarantee).
    """
    s = _STRINGS[lang]
    lines: list[str] = [
        _AUTOGENERATED_HEADER,
        f"# {s['index_h1']}\n",
        f"{s['index_intro']}\n",
        f"| {s['col_id']} | {s['col_category']} | {s['col_statement']} | {s['col_components']} | {s['col_status']} |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in sorted(entries, key=lambda e: e.get("id", "")):
        entry_id = entry.get("id", "")
        category = entry.get("category", "")
        statement = _truncate(str(entry.get("statement", "")))
        components = ", ".join(str(c) for c in entry.get("affected_components", []))
        status = entry.get("status", "")
        # Link the id to the detail page (same language subtree)
        lines.append(
            f"| [{entry_id}]({entry_id}.md) | {category} | {statement} | {components} | {status} |"
        )
    lines.append("")  # trailing newline
    return "\n".join(lines)


def render_detail(entry: dict, lang: str) -> str:
    """
    Render the detail page for a single assumption entry.

    Frontmatter contains `hidden: true` (Open Question #3) plus tags for
    MkDocs Material integration. Body renders all D-33 fields as a description list.
    No timestamps (idempotency guarantee).
    """
    s = _STRINGS[lang]
    entry_id = entry.get("id", "")
    category = entry.get("category", "")
    status = entry.get("status", "")
    superseded_by = entry.get("superseded_by")
    superseded_str = str(superseded_by) if superseded_by is not None else s["null_label"]

    # Frontmatter — deterministic key order (YAML dump not used: we write manually
    # to guarantee stable output without library version sensitivity)
    frontmatter_lines = [
        "---",
        f"id: {entry_id}",
        f"category: {category}",
        f"status: {status}",
        "hidden: true",
        f"tags:",
        f"  - {category}",
        f"  - {status}",
        "---",
        "",
    ]

    # Header and body
    title = f"{s['page_title_prefix']} {entry_id}"
    body_lines: list[str] = [
        _AUTOGENERATED_HEADER,
        "\n".join(frontmatter_lines),
        f"# {title}\n",
        f"**{s['field_id']}:** {entry_id}  ",
        f"**{s['field_category']}:** {entry.get('category', '')}  ",
        f"**{s['field_status']}:** {entry.get('status', '')}  ",
        f"**{s['field_created']}:** {entry.get('created_in_phase', '')}  ",
        f"**{s['field_reviewed']}:** {entry.get('last_reviewed_in_phase', '')}  ",
        f"**{s['field_superseded']}:** {superseded_str}  ",
        "",
        f"## {s['field_statement']}\n",
        str(entry.get("statement", "")).strip(),
        "",
        f"## {s['field_components']}\n",
        ", ".join(str(c) for c in entry.get("affected_components", [])),
        "",
        f"## {s['field_rationale']}\n",
        str(entry.get("rationale", "")).strip(),
        "",
        f"## {s['field_validation']}\n",
        str(entry.get("validation_method", "")).strip(),
        "",
        f"## {s['field_risk']}\n",
        str(entry.get("risk_if_wrong", "")).strip(),
        "",  # final newline
    ]
    return "\n".join(body_lines)


def generate(dry_run: bool = False, check: bool = False) -> tuple[bool, int]:
    """
    Core generation function.

    Returns (success: bool, drift_count: int).
      success = False on I/O error.
      drift_count > 0 means --check would exit 2.
    """
    register_path = WORKSPACE_ROOT / REGISTER
    if not register_path.exists():
        print(
            f"ERROR: register file not found: {REGISTER}",
            file=sys.stderr,
        )
        print(
            "Fix: create docs/assumptions/register.yaml first (Plan 02-03 Task 1).",
            file=sys.stderr,
        )
        return False, 0

    try:
        with register_path.open(encoding="utf-8") as fh:
            entries = yaml.safe_load(fh)
    except yaml.YAMLError as exc:
        print(f"ERROR: cannot parse {REGISTER}: {exc}", file=sys.stderr)
        return False, 0

    if not isinstance(entries, list):
        print(
            f"ERROR: {REGISTER} must be a YAML list at top level, got {type(entries).__name__}.",
            file=sys.stderr,
        )
        return False, 0

    errors: list[str] = []
    drift_paths: list[str] = []

    for lang, output_dir in OUTPUTS.items():
        abs_output_dir = WORKSPACE_ROOT / output_dir

        # --- Index page ---
        index_content = render_index(entries, lang)
        index_path = abs_output_dir / "index.md"
        _write_or_check(
            path=index_path,
            content=index_content,
            dry_run=dry_run,
            check=check,
            errors=errors,
            drift_paths=drift_paths,
        )

        # --- Per-assumption detail pages ---
        for entry in sorted(entries, key=lambda e: e.get("id", "")):
            detail_content = render_detail(entry, lang)
            entry_id = entry.get("id", "")
            detail_path = abs_output_dir / f"{entry_id}.md"
            _write_or_check(
                path=detail_path,
                content=detail_content,
                dry_run=dry_run,
                check=check,
                errors=errors,
                drift_paths=drift_paths,
            )

    if errors:
        print("\nErrors:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return False, len(drift_paths)

    return True, len(drift_paths)


def _write_or_check(
    path: Path,
    content: str,
    dry_run: bool,
    check: bool,
    errors: list[str],
    drift_paths: list[str],
) -> None:
    """
    Write content to path, or perform dry-run / drift check.

    Modifies errors and drift_paths in-place.
    """
    rel = path.relative_to(WORKSPACE_ROOT)

    if check:
        if not path.exists():
            drift_paths.append(str(rel))
            print(f"DRIFT: {rel} (file missing)", file=sys.stderr)
        else:
            try:
                existing = path.read_text(encoding="utf-8")
            except OSError as exc:
                errors.append(f"Cannot read {rel}: {exc}")
                return
            if existing != content:
                drift_paths.append(str(rel))
                print(f"DRIFT: {rel}", file=sys.stderr)
        return

    if dry_run:
        if path.exists():
            try:
                current = path.read_text(encoding="utf-8")
            except OSError as exc:
                errors.append(f"Cannot read {rel}: {exc}")
                return
            if current == content:
                print(f"[dry-run] {rel}: already up to date")
            else:
                print(f"[dry-run] WOULD update {rel}")
        else:
            print(f"[dry-run] WOULD create {rel}")
        return

    # Write
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"Updated {rel}")
    except OSError as exc:
        errors.append(f"Cannot write {rel}: {exc}\n    Fix: check file permissions.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate IT and EN MkDocs assumption pages from docs/assumptions/register.yaml. "
            "Idempotent: double-run produces zero git diff (D-33, RESEARCH Pattern 2). "
            "Detail pages have `hidden: true` (Open Question #3) so they don't appear "
            "in the sidebar nav."
        ),
        epilog=(
            "Run without flags to write pages. "
            "Use --dry-run to preview. "
            "Use --check (exit 2 on drift) in CI as the bilingual drift gate (Plan 07)."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without creating or modifying any files.",
    )
    parser.add_argument(
        "--check",  # add_argument("--check"): drift detection — exit 2 if any file differs
        action="store_true",
        help=(
            "Compare each output file to its would-be content. "
            "Exit 2 if any file is missing or differs from the generated content. "
            "Exit 0 if all files match. Does not write any files."
        ),
    )
    args = parser.parse_args()

    if args.check and args.dry_run:
        print("ERROR: --check and --dry-run are mutually exclusive.", file=sys.stderr)
        sys.exit(1)

    success, drift_count = generate(dry_run=args.dry_run, check=args.check)

    if not success:
        sys.exit(1)

    if args.check and drift_count > 0:
        print(
            f"\n{drift_count} file(s) have drift. Re-run without --check to update.",
            file=sys.stderr,
        )
        sys.exit(2)

    sys.exit(0)


if __name__ == "__main__":
    main()
