/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with dev-mode seeded credentials
         * @description Exchange dev-mode persona credentials for a signed HS256 JWT.
         *
         *     On success returns { access_token, token_type: "bearer", role }.
         *     On failure always returns HTTP 401 with generic detail "invalid_credentials"
         *     to avoid leaking user enumeration information (T-10-01-03 / CR-02).
         */
        post: operations["post_login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the authenticated principal
         * @description Echo the decoded JWT principal: sub, email, role.
         *
         *     Requires a valid Bearer token with any recognised role.  The RBAC dependency
         *     handles 401 (no/invalid token) and 403 (unknown role) automatically.
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current KPI snapshot
         * @description Returns the 6 real KPIs (OEE, MTTR, MTBF, scrap rate, throughput, downtime) computed from TimescaleDB.  Requires one of: operator, shift-supervisor, manager, admin.  OEE is Availability-only (P=1.0, Q=1.0 PoC approximation).
         */
        get: operations["get_kpi_snapshot_v1_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live KPI stream (SSE)
         * @description Server-Sent Events stream emitting kpi_update (every 5 s) and sse_heartbeat (every 30 s). Authenticate via ?token=<JWT>. Allowed roles: operator, shift-supervisor, manager, admin.
         */
        get: operations["stream_kpi_v1_stream_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live approvals stream (SSE)
         * @description Server-Sent Events stream emitting approval_pending, approval_resolved, and sse_heartbeat. Authenticate via ?token=<JWT>.
         */
        get: operations["stream_approvals_v1_stream_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live alerts stream (SSE, HITL-10 rate-limited)
         * @description Server-Sent Events stream emitting alert_new (HITL-10 max 12/hr/persona), rate_limit (when limit exceeded), and sse_heartbeat. Authenticate via ?token=<JWT>.
         */
        get: operations["stream_alerts_v1_stream_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description List approvals — D-55 dashboard endpoint.
         */
        get: operations["list_approvals_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Approval
         * @description Decide a pending approval — atomic UPDATE + supervisor graph resume.
         */
        post: operations["decide_approval_v1_approvals__approval_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Thread */
        post: operations["resume_thread_v1_threads__thread_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quality/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Quality Event
         * @description Accept an operator-submitted QualityEvent and forward to NATS.
         *
         *     Returns 202 Accepted because the downstream QualityInspector agent runs
         *     asynchronously via the NATS consumer wiring (see Plan 06-07 worker loop).
         */
        post: operations["post_quality_event_v1_quality_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/anomaly-detector/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Anomaly Scan
         * @description Run one AnomalyDetector tick via the supervisor graph (OPS-01).
         */
        post: operations["post_anomaly_scan_v1_agents_anomaly_detector_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/production-planner/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Production Plan
         * @description Draft a production schedule via ProductionPlanner (OPS-02).
         *
         *     Returns 202 — the HITL approval is asynchronous; the operator polls
         *     ``GET /v1/approvals`` (or the existing NATS push) and resolves the draft
         *     via ``POST /v1/approvals/{id}/decide``.
         */
        post: operations["post_production_plan_v1_agents_production_planner_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/operator-assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Operator Chat
         * @description One chat turn through the OperatorAssistant ReAct loop (OPS-03).
         */
        post: operations["post_operator_chat_v1_agents_operator_assistant_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/predictive-maintenance/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Pm Score
         * @description Run one PredictiveMaintenance tick via the supervisor graph (MNT-01).
         */
        post: operations["post_pm_score_v1_agents_predictive_maintenance_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/rca-specialist/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Rca Analyze
         * @description Initiate RCA chain via RCASpecialist — always 202 (HITL async, D-RCA-02).
         */
        post: operations["post_rca_analyze_v1_agents_rca_specialist_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/maintenance-coach/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Coach Start
         * @description Open a new coaching intervention (or return awaiting_technician_assignment).
         *
         *     Server generates intervention_id when absent. If technician_id is None,
         *     the supervisor coach node emits a technician_assignment_required HITL
         *     interrupt and the response carries state='awaiting_technician_assignment'.
         *     Client must then call /resume with technician_id to proceed.
         */
        post: operations["post_coach_start_v1_agents_maintenance_coach_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/maintenance-coach/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Coach Step
         * @description Advance an existing coaching intervention by one step.
         *
         *     Returns 409 Conflict if the intervention thread still has technician_id=None
         *     (technician must be assigned first via /resume with technician_id).
         *
         *     Design note: LangGraph replays the checkpoint automatically when the same
         *     thread_id is used in config. The supervisor routes to maintenance-coach
         *     which reads the persisted step state + advances it.
         */
        post: operations["post_coach_step_v1_agents_maintenance_coach_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/maintenance-coach/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Coach Resume
         * @description Resume a coaching intervention after HITL interrupt resolution.
         *
         *     Two paths (Open Q3 RESOLVED in 07-08):
         *       (a) post request_help interrupt — supervisor_input required
         *           → invoke supervisor with Command(resume=supervisor_input) semantics
         *           → state carries escalation_trigger='technician_request' marker
         *       (b) post technician_assignment_required interrupt — technician_id required
         *           → invoke supervisor with Command(update={'technician_id': ...}, resume=True)
         *           → state advances from step 0 with technician assigned
         */
        post: operations["post_coach_resume_v1_agents_maintenance_coach_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/downtime-analyzer/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Da Report
         * @description Run on-demand OEE + Pareto report via DowntimeAnalyzer (MNT-04).
         *
         *     NO Idempotency-Key required — read-only analytics; the same window always
         *     yields the same OEE within CAGG refresh tolerance (maintenance.oee_hourly
         *     CAGG from 07-05 migration 008). Documented as idempotency-not-needed:
         *     the caller can safely retry without risk of duplicate side-effects.
         */
        post: operations["post_da_report_v1_agents_downtime_analyzer_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/shift-handover/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Shift Handover Compile
         * @description Compile shift handover report via ShiftHandover dual-supervisor HITL (D-SH-01).
         *
         *     Returns 202 Accepted immediately (HITL async). Thread_id identifies the LangGraph
         *     thread for subsequent approval workflow via /approvals endpoints.
         */
        post: operations["post_shift_handover_compile_v1_agents_shift_handover_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/training-coach/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Training Session
         * @description Start a new adaptive MCQ quiz session for an operator (TRN-02).
         *
         *     Returns 200 with the session result or 'awaiting_supervisor_signoff' when the
         *     operator passes and HITL interrupt is raised (D-TC-03).
         */
        post: operations["post_training_session_v1_agents_training_coach_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/training-coach/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Training Resume
         * @description Resume a training session after supervisor competency HITL resolution (D-TC-03).
         *
         *     Uses the original thread_id from the session so LangGraph replays the
         *     checkpoint and continues from the interrupt() point.
         */
        post: operations["post_training_resume_v1_agents_training_coach_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/knowledge-curator/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Knowledge Curator Ingest
         * @description Autonomous document curation: dedup detection + staleness flagging (D-KC-04).
         *
         *     NO Idempotency-Key required — fully autonomous read/flag operation;
         *     same document body yields the same dedup/stale verdict (idempotent by nature).
         *     Decision is always Decision.AUTO (D-KC-04 — no HITL gating).
         */
        post: operations["post_knowledge_curator_ingest_v1_agents_knowledge_curator_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/documentation-synthesizer/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Documentation Draft
         * @description Initiate bilingual SOP draft with pre-index HITL gating (D-DS-03, TRN-04).
         *
         *     Returns 202 Accepted — generation and Qdrant indexing happen asynchronously
         *     via the interrupt() / resume pattern. Thread_id identifies the thread for the
         *     subsequent approval workflow.
         */
        post: operations["post_documentation_draft_v1_agents_documentation_synthesizer_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/inventory-manager/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Inventory Check
         * @description Trigger inventory reorder check with HITL supervisor sign-off (SCM-01).
         *
         *     Returns 202 Accepted — HITL async. Thread_id identifies the LangGraph thread
         *     for subsequent supervisor approval via /approvals endpoints.
         */
        post: operations["post_inventory_check_v1_agents_inventory_manager_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/inventory-manager/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Inventory Resume
         * @description Resume inventory reorder check after supervisor HITL resolution (SCM-01).
         *
         *     Uses the original thread_id so LangGraph replays the checkpoint and continues
         *     from the interrupt() point. Returns the final reorder_recommendation.
         */
        post: operations["post_inventory_resume_v1_agents_inventory_manager_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/energy-optimizer/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Energy Optimize
         * @description Trigger energy off-peak scheduling proposal with HITL supervisor sign-off (SCM-02).
         *
         *     Returns 202 Accepted — HITL async. Thread_id identifies the LangGraph thread
         *     for subsequent supervisor approval.
         */
        post: operations["post_energy_optimize_v1_agents_energy_optimizer_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/energy-optimizer/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Energy Resume
         * @description Resume energy optimization after supervisor off-peak sign-off (SCM-02).
         *
         *     Uses the original thread_id so LangGraph replays the checkpoint and continues
         *     from the interrupt() point. Returns the final energy_proposal.
         */
        post: operations["post_energy_resume_v1_agents_energy_optimizer_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/cost-analyzer/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Cost Analyze
         * @description Autonomous cost analysis + OEPV simulation (SCM-03, D-SCM-AUTO).
         *
         *     NO Idempotency-Key required — fully autonomous deterministic operation;
         *     Decision.AUTO, no HITL interrupt. Returns 200 synchronously.
         *     NO resume endpoint (cost-analyzer is read-only, always autonomous).
         */
        post: operations["post_cost_analyze_v1_agents_cost_analyzer_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/demand-forecaster/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Demand Forecast
         * @description Trigger Holt-Winters demand forecast with HITL supervisor sign-off (SCM-04).
         *
         *     Returns 202 Accepted — HITL async. Thread_id identifies the LangGraph thread
         *     for subsequent supervisor approval. On resume, publishes demand_plan to
         *     ProductionPlanner via state['demand_plan'] (Open Question 2 resolution).
         */
        post: operations["post_demand_forecast_v1_agents_demand_forecaster_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/demand-forecaster/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Demand Resume
         * @description Resume demand forecast after supervisor plan sign-off (SCM-04).
         *
         *     Uses the original thread_id so LangGraph replays the checkpoint and continues
         *     from the interrupt() point. Returns the final demand_plan which the gateway
         *     routes to ProductionPlanner via state['demand_plan'] (Open Question 2 resolution).
         */
        post: operations["post_demand_resume_v1_agents_demand_forecaster_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnomalyScanRequestBody
         * @description POST /v1/agents/anomaly-detector/scan body (mirrors ops_anomaly_detector.models.AnomalyScanRequest).
         */
        AnomalyScanRequestBody: {
            /**
             * Window Minutes
             * @description Sliding window in minutes (1..180; default 15).
             * @default 15
             */
            window_minutes: number;
            /**
             * Triggered By
             * @description Caller class — observability tag for the audit row.
             * @default scheduler
             * @enum {string}
             */
            triggered_by: "scheduler" | "operator" | "agent";
        };
        /** ApprovalListResponse */
        ApprovalListResponse: {
            /** Items */
            items: components["schemas"]["ApprovalResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ApprovalResponse
         * @description Mirror of hitl.approvals (D-55) decoupled from DB record shape.
         */
        ApprovalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Thread Id */
            thread_id: string;
            /** Tier */
            tier: string;
            /** Action Type */
            action_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Sla Deadline
             * Format: date-time
             */
            sla_deadline: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By */
            decided_by?: string | null;
            /** Decision */
            decision?: {
                [key: string]: unknown;
            } | null;
            /** Escalated To Id */
            escalated_to_id?: string | null;
        };
        /**
         * CoachResumeRequestHTTP
         * @description Request body for POST /v1/agents/maintenance-coach/resume.
         *
         *     Two resume paths (Open Q3 RESOLVED in 07-08):
         *       (a) post request_help interrupt — ``supervisor_input`` required
         *       (b) post technician_assignment_required interrupt — ``technician_id`` required
         *
         *     At least one of supervisor_input or technician_id MUST be provided (422 otherwise).
         */
        CoachResumeRequestHTTP: {
            /** Intervention Id */
            intervention_id: string;
            /**
             * Supervisor Input
             * @description Supervisor response text (required for post-help resume path)
             */
            supervisor_input?: string | null;
            /**
             * Supervisor Id
             * @description Supervisor identifier for audit trail
             */
            supervisor_id: string;
            /**
             * Technician Id
             * @description Technician ID to assign (required for post-technician-assignment path)
             */
            technician_id?: string | null;
        };
        /**
         * CoachStartRequestHTTP
         * @description Request body for POST /v1/agents/maintenance-coach/start.
         *
         *     ``intervention_id`` is optional at the HTTP boundary — the server generates
         *     a UUID4 when absent. This wraps 07-08's CoachStartRequest which requires
         *     intervention_id; the server fills it in before invoking the supervisor.
         */
        CoachStartRequestHTTP: {
            /**
             * Intervention Id
             * @description Client-generated intervention ID; server generates UUID4 if absent
             */
            intervention_id?: string | null;
            /**
             * Asset Id
             * @description Asset under maintenance (e.g. LOOM-01)
             */
            asset_id: string;
            /**
             * Sop Id
             * @description SOP identifier (e.g. SOP-LOOM-001)
             */
            sop_id: string;
            /**
             * Technician Id
             * @description Optional: omit for RCA auto-open path (Open Q3 RESOLVED in 07-08)
             */
            technician_id?: string | null;
            /**
             * User Roles
             * @description Caller roles for RAG search ACL (Phase 5)
             */
            user_roles?: string[];
        };
        /**
         * CoachStepRequestHTTP
         * @description Request body for POST /v1/agents/maintenance-coach/step.
         */
        CoachStepRequestHTTP: {
            /** Intervention Id */
            intervention_id: string;
            /**
             * Technician Input
             * @description Technician confirmation / notes (cap 4000 — T-V7-coach-injection)
             */
            technician_input: string;
        };
        /**
         * CostAnalyzeRequest
         * @description Request body for POST /v1/agents/cost-analyzer/analyze (SCM-03, D-SCM-AUTO).
         *
         *     Triggers the fully autonomous CostAnalyzer (no HITL, Decision.AUTO).
         */
        CostAnalyzeRequest: {
            /**
             * Ribasso Pct
             * @description Ribasso percentage for OEPV simulation (0–100)
             * @default 10
             */
            ribasso_pct: number;
            /**
             * Pt
             * @description Punteggio tecnico for OEPV simulation (0–100)
             * @default 50
             */
            pt: number;
            /**
             * Oepv Config
             * @description Optional OepvConfig overrides (alpha, beta, gamma, delta weights)
             */
            oepv_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Ts From
             * @description Cost aggregation window start (tz-aware UTC)
             */
            ts_from?: string | null;
            /**
             * Ts To
             * @description Cost aggregation window end (tz-aware UTC)
             */
            ts_to?: string | null;
            /**
             * Window Days
             * @description Cost aggregation window in days (fallback when ts_from/ts_to not set)
             * @default 30
             */
            window_days: number;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 11 — WR-03)
             */
            user_roles?: string[];
        };
        /** DecideRequest */
        DecideRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject" | "escalate";
            /**
             * Motivation
             * @description Free-text motivation. REQUIRED for supervisor/manager/safety_interlock tiers on approve/reject (router-level check).
             * @default
             */
            motivation: string;
            /**
             * Decided By
             * @description Identifier of the human decision-maker
             */
            decided_by: string;
        };
        /** DecideResponse */
        DecideResponse: {
            approval: components["schemas"]["ApprovalResponse"];
            /** Audit Id */
            audit_id?: string | null;
            /** Resumed */
            resumed: boolean;
        };
        /**
         * DemandForecastRequest
         * @description Request body for POST /v1/agents/demand-forecaster/forecast (SCM-04).
         *
         *     Triggers DemandForecaster Holt-Winters HITL flow.
         */
        DemandForecastRequest: {
            /**
             * Sku Groups
             * @description SKU groups to forecast (e.g. ['jersey', 'twill']); None means defaults
             */
            sku_groups?: string[] | null;
            /**
             * Horizon
             * @description Forecast horizon in months (1–36)
             * @default 6
             */
            horizon: number;
            /**
             * Months Back
             * @description Historical months to use for training (6–120)
             * @default 24
             */
            months_back: number;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 11 — WR-03)
             */
            user_roles?: string[];
        };
        /**
         * DemandResumeRequest
         * @description Request body for POST /v1/agents/demand-forecaster/resume (SCM-04).
         *
         *     Resume demand forecasting after supervisor plan sign-off.
         *     Publishes demand_plan to ProductionPlanner via returned state.
         */
        DemandResumeRequest: {
            /**
             * Thread Id
             * @description LangGraph thread_id from the original forecast (supply.demand-forecaster.<uuid>)
             */
            thread_id: string;
            /**
             * Decision
             * @description Supervisor demand-plan decision (e.g. 'approved', 'rejected')
             */
            decision: string;
            /**
             * Decision Actor
             * @description Identity of the supervisor who made the decision
             */
            decision_actor: string;
        };
        /**
         * DocumentationDraftRequest
         * @description Request body for POST /v1/agents/documentation-synthesizer/draft (TRN-04, D-DS-03).
         *
         *     Triggers bilingual SOP draft generation with pre-index HITL gating.
         */
        DocumentationDraftRequest: {
            /**
             * Failure Mode
             * @description Failure mode description for SOP context (D-DS-02)
             */
            failure_mode: string;
            /**
             * Asset Id
             * @description Asset identifier for event aggregation (e.g. 'LOOM-01')
             */
            asset_id: string;
            /**
             * Window Days
             * @description Historical event window in days for aggregation (default 30)
             * @default 30
             */
            window_days: number;
        };
        /**
         * EnergyOptimizeRequest
         * @description Request body for POST /v1/agents/energy-optimizer/optimize (SCM-02).
         *
         *     Triggers EnergyOptimizer off-peak scheduling HITL flow.
         */
        EnergyOptimizeRequest: {
            /**
             * Process
             * @description Factory process to analyse (e.g. 'dyeing', 'spinning'); None means all
             */
            process?: string | null;
            /**
             * Ts From
             * @description Time-window start (tz-aware UTC) for energy readings
             */
            ts_from?: string | null;
            /**
             * Ts To
             * @description Time-window end (tz-aware UTC) for energy readings
             */
            ts_to?: string | null;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 11 — WR-03)
             */
            user_roles?: string[];
        };
        /**
         * EnergyResumeRequest
         * @description Request body for POST /v1/agents/energy-optimizer/resume (SCM-02).
         *
         *     Resume an energy optimization after supervisor off-peak sign-off.
         */
        EnergyResumeRequest: {
            /**
             * Thread Id
             * @description LangGraph thread_id from the original optimize (supply.energy-optimizer.<uuid>)
             */
            thread_id: string;
            /**
             * Decision
             * @description Supervisor off-peak proposal decision (e.g. 'approved', 'rejected')
             */
            decision: string;
            /**
             * Decision Actor
             * @description Identity of the supervisor who made the decision
             */
            decision_actor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description JSON body for /v1/health and /v1/ready.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Dependencies */
            dependencies: {
                [key: string]: "up" | "down";
            };
        };
        /**
         * InventoryCheckRequest
         * @description Request body for POST /v1/agents/inventory-manager/check (SCM-01).
         *
         *     Manual trigger for InventoryManager single-supervisor HITL flow.
         */
        InventoryCheckRequest: {
            /**
             * Sku Ids
             * @description Optional list of SKU identifiers to check; None means all SKUs
             */
            sku_ids?: string[] | null;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 11 — WR-03)
             */
            user_roles?: string[];
        };
        /**
         * InventoryResumeRequest
         * @description Request body for POST /v1/agents/inventory-manager/resume (SCM-01).
         *
         *     Resume an inventory check after supervisor reorder sign-off.
         */
        InventoryResumeRequest: {
            /**
             * Thread Id
             * @description LangGraph thread_id from the original check (supply.inventory-manager.<uuid>)
             */
            thread_id: string;
            /**
             * Decision
             * @description Supervisor reorder decision (e.g. 'approved', 'rejected')
             */
            decision: string;
            /**
             * Decision Actor
             * @description Identity of the supervisor who made the decision
             */
            decision_actor: string;
        };
        /**
         * KnowledgeCuratorIngestRequest
         * @description Request body for POST /v1/agents/knowledge-curator/ingest (D-KC-04).
         *
         *     Triggers autonomous dedup + staleness flagging. No HITL gating.
         */
        KnowledgeCuratorIngestRequest: {
            /**
             * Document Id
             * @description Unique document identifier (client-provided or SHA256 of content)
             */
            document_id: string;
            /**
             * Document Text
             * @description Full document text to curate (max 100 KiB)
             */
            document_text: string;
            /**
             * Doc Type
             * @description Document type (e.g. 'sop', 'manual', 'training_material')
             */
            doc_type: string;
            /**
             * Last Updated
             * Format: date-time
             * @description Document last-updated timestamp (tz-aware) for staleness check
             */
            last_updated: string;
            /**
             * Source Uri
             * @description Document source URI for citation traceability (TRN-05)
             */
            source_uri: string;
            /**
             * User Roles
             * @description Caller roles for future ACL enforcement (Phase 11)
             */
            user_roles?: string[];
        };
        /**
         * KpiSnapshot
         * @description Snapshot of the 6 real KPIs computed from TimescaleDB.
         *
         *     All fields are float | None: None indicates no data was available for
         *     the computed window (no downtime events, no orders, etc.).
         *
         *     Units:
         *         oee          — percentage [0, 100]
         *         mttr         — minutes
         *         mtbf         — hours
         *         scrap_rate   — percentage [0, 100]
         *         throughput   — kg/h
         *         downtime     — percentage [0, 100]
         */
        KpiSnapshot: {
            /** Oee */
            oee: number | null;
            /** Mttr */
            mttr: number | null;
            /** Mtbf */
            mtbf: number | null;
            /** Scrap Rate */
            scrap_rate: number | null;
            /** Throughput */
            throughput: number | null;
            /** Downtime */
            downtime: number | null;
        };
        /**
         * LoginRequest
         * @description Credentials for POST /auth/login (dev-mode seeded personas only).
         *
         *     extra="forbid" and frozen=True enforce strict input validation (CR-03).
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Successful login response containing a signed JWT.
         */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /** Role */
            role: string;
        };
        /**
         * MeResponse
         * @description Principal echo for GET /auth/me.
         */
        MeResponse: {
            /** Sub */
            sub: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /**
         * OperatorChatRequestBody
         * @description POST /v1/agents/operator-assistant/chat body (mirrors ops_operator_assistant.models.OperatorChatRequest).
         */
        OperatorChatRequestBody: {
            /**
             * Query
             * @description Operator question (free text, IT or EN).
             */
            query: string;
            /**
             * User Roles
             * @description RBAC roles propagated to RagSearchTool ACL pre-filter.
             */
            user_roles: string[];
            /**
             * Thread Id
             * @description LangGraph thread_id for checkpoint persistence.
             */
            thread_id: string;
        };
        /**
         * PMScoreRequest
         * @description Request body for POST /v1/agents/predictive-maintenance/score (MNT-01).
         */
        PMScoreRequest: {
            /** Asset Id */
            asset_id: string;
            /**
             * Triggered By Action Id
             * @description Upstream AnomalyDetector audit row action_id for MNT-06 chain
             */
            triggered_by_action_id?: string | null;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 5)
             */
            user_roles: string[];
        };
        /**
         * PMScoreResponse
         * @description Response envelope for POST /v1/agents/predictive-maintenance/score.
         */
        PMScoreResponse: {
            /** @description RUL estimate (None when agent escalated to HITL supervisor) */
            rul_estimate?: components["schemas"]["RULEstimate"] | null;
            /**
             * Thread Id
             * @description LangGraph thread_id for this invocation
             */
            thread_id: string;
        };
        /**
         * PlanRequestBody
         * @description POST /v1/agents/production-planner/plan body (mirrors ops_production_planner.models.PlanRequest).
         */
        PlanRequestBody: {
            /**
             * Strategy
             * @description Scheduling strategy: 'spt' or 'edd'.
             * @enum {string}
             */
            strategy: "spt" | "edd";
            /**
             * Horizon Days
             * @description Horizon window in days (1..30).
             */
            horizon_days: number;
            /**
             * User Roles
             * @description Operator roles for RAG ACL pre-filter (Phase 5 D-72).
             */
            user_roles?: string[];
        };
        /**
         * QualityEventAcceptedResponse
         * @description 202 envelope returned by POST /v1/quality/events.
         */
        QualityEventAcceptedResponse: {
            /** Accepted */
            accepted: boolean;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /**
         * QualityEventOperatorRequest
         * @description Operator-facing QualityEvent payload (T-V6-source-spoof mitigation).
         *
         *     Mirrors ``sft_domain.ops.quality.QualityEvent`` but DELIBERATELY OMITS:
         *
         *       * ``event_id``  — server generates fresh UUID4.
         *       * ``source``    — server forces "operator"; reject unknown keys via
         *                         ``extra="forbid"`` so a client cannot smuggle
         *                         ``source="simulator"`` into the publish payload.
         *
         *     All other validation rules (regex on dye_lot_id, defect_type Literal,
         *     tz-aware timestamp, bounded defect_length_inches) are mirrored.
         */
        QualityEventOperatorRequest: {
            /**
             * Asset Id
             * @description Asset ID
             */
            asset_id: string;
            /**
             * Dye Lot Id
             * @description Dye-lot identifier (D-QI-04 regex).
             */
            dye_lot_id: string;
            /**
             * Defect Type
             * @description Tipo difetto (7-defect taxonomy)
             * @enum {string}
             */
            defect_type: "broken_end" | "mispick" | "slub" | "neppy" | "selvage_fault" | "shade_deviation" | "unlevel_dyeing";
            /**
             * Defect Length Inches
             * @description Defect length in inches (>=0)
             */
            defect_length_inches: number;
            /**
             * Full Width
             * @description Full-width (selvedge-to-selvedge)
             * @default false
             */
            full_width: boolean;
            /**
             * Position Meters
             * @description Linear position on the roll (meters)
             */
            position_meters: number;
            /**
             * Timestamp
             * Format: date-time
             * @description UTC tz-aware observation
             */
            timestamp: string;
        };
        /**
         * RCAAnalyzeRequest
         * @description Request body for POST /v1/agents/rca-specialist/analyze (MNT-02).
         */
        RCAAnalyzeRequest: {
            /**
             * Problem Statement
             * @description Problem description (min 10 chars for meaningful RCA)
             */
            problem_statement: string;
            /**
             * Downtime Event Id
             * @description Optional downtime_event_id from maintenance.downtime_events (07-05)
             */
            downtime_event_id?: string | null;
            /**
             * Asset Id
             * @description Optional asset_id scope filter
             */
            asset_id?: string | null;
            /**
             * User Roles
             * @description Caller roles (min 1 required for ACL)
             */
            user_roles: string[];
            /**
             * Lang
             * @description RCA report language (IT default per D-RCA-01)
             * @default it
             * @enum {string}
             */
            lang: "it" | "en";
        };
        /**
         * RCAAnalyzeResponse
         * @description Response envelope for POST /v1/agents/rca-specialist/analyze.
         */
        RCAAnalyzeResponse: {
            /**
             * Chain Id
             * @description RCAChain UUID4 (None until supervisor approves post-HITL)
             */
            chain_id?: string | null;
            /**
             * Thread Id
             * @description LangGraph thread_id for this invocation
             */
            thread_id: string;
            /**
             * Hitl Status
             * @description Always 'supervisor_pending' per D-RCA-02 always-HITL contract
             * @constant
             */
            hitl_status: "supervisor_pending";
            /**
             * Validation Exhausted
             * @description True when 07-07 retry budget (3 attempts) was exhausted before escalation
             * @default false
             */
            validation_exhausted: boolean;
        };
        /**
         * RULEstimate
         * @description Remaining Useful Life estimate per D-PM-04.
         *
         *     Frozen + extra=forbid ensures the estimate is immutable once constructed
         *     and no undocumented fields can be injected downstream.
         *
         *     Fields
         *     ------
         *     estimate_id:
         *         str(uuid4()) — unique identifier for this estimate.
         *     asset_id:
         *         Textile asset identifier (e.g. 'LOOM-01').
         *     rul_cycles:
         *         Point estimate of remaining useful cycles (>= 0).
         *     confidence_band_lower:
         *         Lower bound of the ±10% CI band (>= 0).
         *     confidence_band_upper:
         *         Upper bound of the ±10% CI band (>= 0).
         *     health_index:
         *         Derived deterministically from rul_cycles: clamp(rul_cycles / 125.0, 0.0, 1.0).
         *         Bound to [0.0, 1.0]; values < 0.3 trigger the HITL supervisor gate.
         *     recommended_action:
         *         Human-readable IT intervention message populated ONLY when health_index < 0.3
         *         (HITL branch). None for AUTO branch.
         *     triggered_by_action_id:
         *         UUID string of the upstream AnomalyDetector audit row's action_id.
         *         Enables MNT-06 SQL JOIN audit chain reconstruction.
         *     model_version:
         *         Identifier of the loaded joblib model (e.g. 'ridge-fd001-fd003-v1.0').
         *     created_at:
         *         UTC tz-aware timestamp of estimate creation. Naive datetime rejected
         *         (Pattern S-6 / T-V7-pm-naive-datetime).
         */
        RULEstimate: {
            /**
             * Estimate Id
             * @description str(uuid4())
             */
            estimate_id: string;
            /**
             * Asset Id
             * @description Asset identifier (e.g. LOOM-01)
             */
            asset_id: string;
            /**
             * Rul Cycles
             * @description Remaining useful cycles point estimate
             */
            rul_cycles: number;
            /**
             * Confidence Band Lower
             * @description CI lower bound (>=0)
             */
            confidence_band_lower: number;
            /**
             * Confidence Band Upper
             * @description CI upper bound (>=0)
             */
            confidence_band_upper: number;
            /**
             * Health Index
             * @description clamp(rul_cycles / 125.0, 0.0, 1.0)
             */
            health_index: number;
            /**
             * Recommended Action
             * @description HITL-branch IT intervention message; None for AUTO
             */
            recommended_action?: string | null;
            /**
             * Triggered By Action Id
             * @description AnomalyDetector audit row action_id for MNT-06 chain
             */
            triggered_by_action_id?: string | null;
            /**
             * Model Version
             * @description Loaded model identifier
             */
            model_version: string;
            /**
             * Created At
             * Format: date-time
             * @description UTC tz-aware timestamp
             */
            created_at: string;
        };
        /** ResumeRequest */
        ResumeRequest: {
            /**
             * Approval Id
             * Format: uuid
             * @description Pending hitl.approvals row id
             */
            approval_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject" | "escalate";
            /**
             * Motivation
             * @description Mandatory on supervisor/manager/safety_interlock tiers
             * @default
             */
            motivation: string;
            /** Decided By */
            decided_by: string;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /** Thread Id */
            thread_id: string;
            /** State After */
            state_after: {
                [key: string]: unknown;
            };
            /** Audit Ids */
            audit_ids: string[];
            /** Completed */
            completed: boolean;
        };
        /**
         * ShiftHandoverCompileRequest
         * @description Request body for POST /v1/agents/shift-handover/compile (TRN-03, D-SH-01).
         *
         *     Manual trigger for the ShiftHandover dual-supervisor HITL flow.
         *     Complements the NATS-scheduled trigger (D-SH-01).
         */
        ShiftHandoverCompileRequest: {
            /**
             * Shift Start
             * Format: date-time
             * @description Shift window start (tz-aware UTC)
             */
            shift_start: string;
            /**
             * Shift End
             * Format: date-time
             * @description Shift window end (tz-aware UTC)
             */
            shift_end: string;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement (Phase 11)
             */
            user_roles: string[];
        };
        /**
         * TrainingResumeRequest
         * @description Request body for POST /v1/agents/training-coach/resume (TRN-02, D-TC-03).
         *
         *     Resume a training session after supervisor competency HITL sign-off.
         */
        TrainingResumeRequest: {
            /**
             * Thread Id
             * @description LangGraph thread_id from the original session (knowledge.training-coach.<uuid>)
             */
            thread_id: string;
            /**
             * Decision
             * @description Supervisor competency decision (e.g. 'approved', 'rejected')
             */
            decision: string;
        };
        /**
         * TrainingSessionRequest
         * @description Request body for POST /v1/agents/training-coach/session (TRN-02, D-TC-01).
         *
         *     Starts a new adaptive MCQ quiz session for the operator.
         */
        TrainingSessionRequest: {
            /**
             * Persona Role
             * @description Operator role from SOP frontmatter (D-X-03, D-TC-01)
             */
            persona_role: string;
            /**
             * User Roles
             * @description Caller roles for ACL enforcement
             */
            user_roles: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * _ReportRequestHTTP
         * @description HTTP wrapper for ReportRequest that enforces window_end > window_start at ingestion.
         *
         *     ReportRequest (from 07-09) does not validate window order (OEEReport does).
         *     This wrapper adds the cross-field validator so the 422 fires at request
         *     parsing rather than at response serialization.
         */
        _ReportRequestHTTP: {
            /**
             * Window Start
             * Format: date-time
             * @description Window start (tz-aware).
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             * @description Window end (tz-aware, > window_start).
             */
            window_end: string;
            /**
             * By Asset
             * @description Include per-asset breakdown.
             * @default false
             */
            by_asset: boolean;
            /**
             * Top N Pareto
             * @description Top-N Pareto entries to return (1..100; T-V7-da-pareto-flood cap).
             * @default 10
             */
            top_n_pareto: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_kpi_snapshot_v1_kpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiSnapshot"];
                };
            };
        };
    };
    stream_kpi_v1_stream_kpi_get: {
        parameters: {
            query?: {
                /** @description JWT token (SSE — EventSource cannot set headers) */
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_approvals_v1_stream_approvals_get: {
        parameters: {
            query?: {
                /** @description JWT token (SSE — EventSource cannot set headers) */
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_alerts_v1_stream_alerts_get: {
        parameters: {
            query?: {
                /** @description JWT token (SSE — EventSource cannot set headers) */
                token?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_v1_approvals_get: {
        parameters: {
            query?: {
                /** @description Filter by tier (D-55) */
                tier?: ("operator" | "supervisor" | "manager" | "safety_interlock") | null;
                /** @description Filter by ApprovalStatus */
                status?: ("pending" | "approved" | "rejected" | "escalated" | "timed_out") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_v1_approvals__approval_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_thread_v1_threads__thread_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_quality_event_v1_quality_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityEventOperatorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityEventAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_anomaly_scan_v1_agents_anomaly_detector_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnomalyScanRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_production_plan_v1_agents_production_planner_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_operator_chat_v1_agents_operator_assistant_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorChatRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_pm_score_v1_agents_predictive_maintenance_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PMScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PMScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_rca_analyze_v1_agents_rca_specialist_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RCAAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RCAAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_coach_start_v1_agents_maintenance_coach_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachStartRequestHTTP"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_coach_step_v1_agents_maintenance_coach_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachStepRequestHTTP"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_coach_resume_v1_agents_maintenance_coach_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachResumeRequestHTTP"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_da_report_v1_agents_downtime_analyzer_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_ReportRequestHTTP"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_shift_handover_compile_v1_agents_shift_handover_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftHandoverCompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_training_session_v1_agents_training_coach_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_training_resume_v1_agents_training_coach_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_knowledge_curator_ingest_v1_agents_knowledge_curator_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeCuratorIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_documentation_draft_v1_agents_documentation_synthesizer_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentationDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_inventory_check_v1_agents_inventory_manager_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_inventory_resume_v1_agents_inventory_manager_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_energy_optimize_v1_agents_energy_optimizer_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnergyOptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_energy_resume_v1_agents_energy_optimizer_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnergyResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cost_analyze_v1_agents_cost_analyzer_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_demand_forecast_v1_agents_demand_forecaster_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_demand_resume_v1_agents_demand_forecaster_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemandResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
